#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : git
Version  : 2.33.0
Release  : 182
URL      : file:///aot/build/clearlinux/packages/git/git-v2.33.0.tar.gz
Source0  : file:///aot/build/clearlinux/packages/git/git-v2.33.0.tar.gz
Summary  : the fast distributed version control system
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
BuildRequires : asciidoc
BuildRequires : buildreq-cmake
BuildRequires : buildreq-golang
BuildRequires : curl-dev
BuildRequires : docbook-xml
BuildRequires : expat-dev
BuildRequires : expat-staticdev
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : libxslt-bin
BuildRequires : nghttp2-dev
BuildRequires : openssl-dev
BuildRequires : openssl-staticdev
BuildRequires : pcre2-dev
BuildRequires : pcre2-staticdev
BuildRequires : perl-Error
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : tcl
BuildRequires : tk
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : util-linux-staticdev
BuildRequires : xmlto
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
Patch1: 0001-Set-default-autocorrect-timeout-to-1.5-seconds.patch
Patch2: 0002-Fix-expected-result-for-a-for-each-ref-test.patch

%description
Core Git Tests
==============
This directory holds many test scripts for core Git tools.  The
first part of this short document describes how to run the tests
and read their output.

%prep
%setup -q -n git
cd %{_builddir}/git
%patch1 -p1
%patch2 -p1
pushd %{_builddir}
cp -a %{_builddir}/git buildavx2
popd

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629554286
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=16 -fno-semantic-interposition -mprefer-vector-width=256 "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=16 -fno-semantic-interposition -mprefer-vector-width=256 "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=16 -fno-semantic-interposition -mprefer-vector-width=256 "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=16 -fno-semantic-interposition -mprefer-vector-width=256 "
make  %{?_smp_mflags}    V=1 VERBOSE=1

pushd ../buildavx2
export CFLAGS="$CFLAGS -m64 -march=native -mtune=native"
export CXXFLAGS="$CXXFLAGS -m64 -march=native -mtune=native"
export FFLAGS="$FFLAGS -m64 -march=native -mtune=native"
export FCFLAGS="$FCFLAGS -m64 -march=native -mtune=native"
export LDFLAGS="$LDFLAGS -m64 -march=native -mtune=native"
make  %{?_smp_mflags}    V=1 VERBOSE=1
popd

%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
make %{?_smp_mflags} test

%install
export SOURCE_DATE_EPOCH=1629554286
rm -rf %{buildroot}
pushd ../buildavx2/
%make_install_avx2
popd
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/gitk
rm -f %{buildroot}/usr/lib/perl5/site_perl/*/x86_64-linux-thread-multi/auto/Git/.packlist
rm -f %{buildroot}/usr/libexec/git-core/git-gui
rm -f %{buildroot}/usr/libexec/git-core/git-gui--askpass
rm -f %{buildroot}/usr/share/man/man1/git-gui.1
rm -f %{buildroot}/usr/share/man/man1/gitk.1
## install_append content
install -D -m 00644 contrib/completion/git-completion.bash %{buildroot}/usr/share/bash-completion/completions/git
install -D -m 00644 contrib/completion/git-prompt.sh %{buildroot}/usr/share/git-core/git-prompt.sh
make -C Documentation DESTDIR=%{buildroot} %{?_smp_mflags} man install
make -C contrib/subtree DESTDIR=%{buildroot} %{?_smp_mflags} install
# Remove files packaged in 'git-gui' not removed via 'excludes' file.
find %{buildroot}/usr/share/git-gui -delete
find %{buildroot}/usr/share/gitk -delete
# The 'make' commands above re-install these
rm -f %{buildroot}/usr/share/man/man1/git-gui.1
rm -f %{buildroot}/usr/share/man/man1/gitk.1
## install_append end

%files
%defattr(-,root,root,-)
